// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PbStudent.proto

package me.kay.grpc;

public interface AgeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:me.kay.proto.AgeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 student_age = 1;</code>
   * @return The studentAge.
   */
  int getStudentAge();
}
