// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PbStudent.proto

package me.kay.grpc;

public interface NameRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:me.kay.proto.NameRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string student_name = 1;</code>
   * @return The studentName.
   */
  java.lang.String getStudentName();
  /**
   * <code>string student_name = 1;</code>
   * @return The bytes for studentName.
   */
  com.google.protobuf.ByteString
      getStudentNameBytes();
}
