// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Contract.proto

package me.kay.protobuf.proto;

/**
 * Protobuf type {@code me.kay.proto.CreateContract}
 */
public  final class CreateContract extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:me.kay.proto.CreateContract)
    CreateContractOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateContract.newBuilder() to construct.
  private CreateContract(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateContract() {
    ownerAddress_ = "";
    contractAbi_ = "";
    contractCode_ = "";
    contractParams_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateContract();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreateContract(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            ownerAddress_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            contractAbi_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            contractCode_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            contractParams_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return me.kay.protobuf.proto.Contract.internal_static_me_kay_proto_CreateContract_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return me.kay.protobuf.proto.Contract.internal_static_me_kay_proto_CreateContract_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            me.kay.protobuf.proto.CreateContract.class, me.kay.protobuf.proto.CreateContract.Builder.class);
  }

  public static final int OWNER_ADDRESS_FIELD_NUMBER = 1;
  private volatile java.lang.Object ownerAddress_;
  /**
   * <code>string owner_address = 1;</code>
   * @return The ownerAddress.
   */
  public java.lang.String getOwnerAddress() {
    java.lang.Object ref = ownerAddress_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ownerAddress_ = s;
      return s;
    }
  }
  /**
   * <code>string owner_address = 1;</code>
   * @return The bytes for ownerAddress.
   */
  public com.google.protobuf.ByteString
      getOwnerAddressBytes() {
    java.lang.Object ref = ownerAddress_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ownerAddress_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTRACT_ABI_FIELD_NUMBER = 2;
  private volatile java.lang.Object contractAbi_;
  /**
   * <code>string contract_abi = 2;</code>
   * @return The contractAbi.
   */
  public java.lang.String getContractAbi() {
    java.lang.Object ref = contractAbi_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      contractAbi_ = s;
      return s;
    }
  }
  /**
   * <code>string contract_abi = 2;</code>
   * @return The bytes for contractAbi.
   */
  public com.google.protobuf.ByteString
      getContractAbiBytes() {
    java.lang.Object ref = contractAbi_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      contractAbi_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTRACT_CODE_FIELD_NUMBER = 3;
  private volatile java.lang.Object contractCode_;
  /**
   * <code>string contract_code = 3;</code>
   * @return The contractCode.
   */
  public java.lang.String getContractCode() {
    java.lang.Object ref = contractCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      contractCode_ = s;
      return s;
    }
  }
  /**
   * <code>string contract_code = 3;</code>
   * @return The bytes for contractCode.
   */
  public com.google.protobuf.ByteString
      getContractCodeBytes() {
    java.lang.Object ref = contractCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      contractCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTRACT_PARAMS_FIELD_NUMBER = 4;
  private volatile java.lang.Object contractParams_;
  /**
   * <code>string contract_params = 4;</code>
   * @return The contractParams.
   */
  public java.lang.String getContractParams() {
    java.lang.Object ref = contractParams_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      contractParams_ = s;
      return s;
    }
  }
  /**
   * <code>string contract_params = 4;</code>
   * @return The bytes for contractParams.
   */
  public com.google.protobuf.ByteString
      getContractParamsBytes() {
    java.lang.Object ref = contractParams_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      contractParams_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getOwnerAddressBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ownerAddress_);
    }
    if (!getContractAbiBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, contractAbi_);
    }
    if (!getContractCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, contractCode_);
    }
    if (!getContractParamsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, contractParams_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getOwnerAddressBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ownerAddress_);
    }
    if (!getContractAbiBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, contractAbi_);
    }
    if (!getContractCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, contractCode_);
    }
    if (!getContractParamsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, contractParams_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof me.kay.protobuf.proto.CreateContract)) {
      return super.equals(obj);
    }
    me.kay.protobuf.proto.CreateContract other = (me.kay.protobuf.proto.CreateContract) obj;

    if (!getOwnerAddress()
        .equals(other.getOwnerAddress())) return false;
    if (!getContractAbi()
        .equals(other.getContractAbi())) return false;
    if (!getContractCode()
        .equals(other.getContractCode())) return false;
    if (!getContractParams()
        .equals(other.getContractParams())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OWNER_ADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getOwnerAddress().hashCode();
    hash = (37 * hash) + CONTRACT_ABI_FIELD_NUMBER;
    hash = (53 * hash) + getContractAbi().hashCode();
    hash = (37 * hash) + CONTRACT_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getContractCode().hashCode();
    hash = (37 * hash) + CONTRACT_PARAMS_FIELD_NUMBER;
    hash = (53 * hash) + getContractParams().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static me.kay.protobuf.proto.CreateContract parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static me.kay.protobuf.proto.CreateContract parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static me.kay.protobuf.proto.CreateContract parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static me.kay.protobuf.proto.CreateContract parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static me.kay.protobuf.proto.CreateContract parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static me.kay.protobuf.proto.CreateContract parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static me.kay.protobuf.proto.CreateContract parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static me.kay.protobuf.proto.CreateContract parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static me.kay.protobuf.proto.CreateContract parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static me.kay.protobuf.proto.CreateContract parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static me.kay.protobuf.proto.CreateContract parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static me.kay.protobuf.proto.CreateContract parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(me.kay.protobuf.proto.CreateContract prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code me.kay.proto.CreateContract}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:me.kay.proto.CreateContract)
      me.kay.protobuf.proto.CreateContractOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.kay.protobuf.proto.Contract.internal_static_me_kay_proto_CreateContract_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.kay.protobuf.proto.Contract.internal_static_me_kay_proto_CreateContract_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.kay.protobuf.proto.CreateContract.class, me.kay.protobuf.proto.CreateContract.Builder.class);
    }

    // Construct using me.kay.protobuf.proto.CreateContract.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      ownerAddress_ = "";

      contractAbi_ = "";

      contractCode_ = "";

      contractParams_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return me.kay.protobuf.proto.Contract.internal_static_me_kay_proto_CreateContract_descriptor;
    }

    @java.lang.Override
    public me.kay.protobuf.proto.CreateContract getDefaultInstanceForType() {
      return me.kay.protobuf.proto.CreateContract.getDefaultInstance();
    }

    @java.lang.Override
    public me.kay.protobuf.proto.CreateContract build() {
      me.kay.protobuf.proto.CreateContract result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public me.kay.protobuf.proto.CreateContract buildPartial() {
      me.kay.protobuf.proto.CreateContract result = new me.kay.protobuf.proto.CreateContract(this);
      result.ownerAddress_ = ownerAddress_;
      result.contractAbi_ = contractAbi_;
      result.contractCode_ = contractCode_;
      result.contractParams_ = contractParams_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof me.kay.protobuf.proto.CreateContract) {
        return mergeFrom((me.kay.protobuf.proto.CreateContract)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(me.kay.protobuf.proto.CreateContract other) {
      if (other == me.kay.protobuf.proto.CreateContract.getDefaultInstance()) return this;
      if (!other.getOwnerAddress().isEmpty()) {
        ownerAddress_ = other.ownerAddress_;
        onChanged();
      }
      if (!other.getContractAbi().isEmpty()) {
        contractAbi_ = other.contractAbi_;
        onChanged();
      }
      if (!other.getContractCode().isEmpty()) {
        contractCode_ = other.contractCode_;
        onChanged();
      }
      if (!other.getContractParams().isEmpty()) {
        contractParams_ = other.contractParams_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      me.kay.protobuf.proto.CreateContract parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (me.kay.protobuf.proto.CreateContract) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object ownerAddress_ = "";
    /**
     * <code>string owner_address = 1;</code>
     * @return The ownerAddress.
     */
    public java.lang.String getOwnerAddress() {
      java.lang.Object ref = ownerAddress_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ownerAddress_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string owner_address = 1;</code>
     * @return The bytes for ownerAddress.
     */
    public com.google.protobuf.ByteString
        getOwnerAddressBytes() {
      java.lang.Object ref = ownerAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ownerAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string owner_address = 1;</code>
     * @param value The ownerAddress to set.
     * @return This builder for chaining.
     */
    public Builder setOwnerAddress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ownerAddress_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string owner_address = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOwnerAddress() {
      
      ownerAddress_ = getDefaultInstance().getOwnerAddress();
      onChanged();
      return this;
    }
    /**
     * <code>string owner_address = 1;</code>
     * @param value The bytes for ownerAddress to set.
     * @return This builder for chaining.
     */
    public Builder setOwnerAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ownerAddress_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object contractAbi_ = "";
    /**
     * <code>string contract_abi = 2;</code>
     * @return The contractAbi.
     */
    public java.lang.String getContractAbi() {
      java.lang.Object ref = contractAbi_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contractAbi_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string contract_abi = 2;</code>
     * @return The bytes for contractAbi.
     */
    public com.google.protobuf.ByteString
        getContractAbiBytes() {
      java.lang.Object ref = contractAbi_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contractAbi_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string contract_abi = 2;</code>
     * @param value The contractAbi to set.
     * @return This builder for chaining.
     */
    public Builder setContractAbi(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      contractAbi_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string contract_abi = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearContractAbi() {
      
      contractAbi_ = getDefaultInstance().getContractAbi();
      onChanged();
      return this;
    }
    /**
     * <code>string contract_abi = 2;</code>
     * @param value The bytes for contractAbi to set.
     * @return This builder for chaining.
     */
    public Builder setContractAbiBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      contractAbi_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object contractCode_ = "";
    /**
     * <code>string contract_code = 3;</code>
     * @return The contractCode.
     */
    public java.lang.String getContractCode() {
      java.lang.Object ref = contractCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contractCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string contract_code = 3;</code>
     * @return The bytes for contractCode.
     */
    public com.google.protobuf.ByteString
        getContractCodeBytes() {
      java.lang.Object ref = contractCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contractCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string contract_code = 3;</code>
     * @param value The contractCode to set.
     * @return This builder for chaining.
     */
    public Builder setContractCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      contractCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string contract_code = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearContractCode() {
      
      contractCode_ = getDefaultInstance().getContractCode();
      onChanged();
      return this;
    }
    /**
     * <code>string contract_code = 3;</code>
     * @param value The bytes for contractCode to set.
     * @return This builder for chaining.
     */
    public Builder setContractCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      contractCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object contractParams_ = "";
    /**
     * <code>string contract_params = 4;</code>
     * @return The contractParams.
     */
    public java.lang.String getContractParams() {
      java.lang.Object ref = contractParams_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contractParams_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string contract_params = 4;</code>
     * @return The bytes for contractParams.
     */
    public com.google.protobuf.ByteString
        getContractParamsBytes() {
      java.lang.Object ref = contractParams_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contractParams_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string contract_params = 4;</code>
     * @param value The contractParams to set.
     * @return This builder for chaining.
     */
    public Builder setContractParams(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      contractParams_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string contract_params = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearContractParams() {
      
      contractParams_ = getDefaultInstance().getContractParams();
      onChanged();
      return this;
    }
    /**
     * <code>string contract_params = 4;</code>
     * @param value The bytes for contractParams to set.
     * @return This builder for chaining.
     */
    public Builder setContractParamsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      contractParams_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:me.kay.proto.CreateContract)
  }

  // @@protoc_insertion_point(class_scope:me.kay.proto.CreateContract)
  private static final me.kay.protobuf.proto.CreateContract DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new me.kay.protobuf.proto.CreateContract();
  }

  public static me.kay.protobuf.proto.CreateContract getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateContract>
      PARSER = new com.google.protobuf.AbstractParser<CreateContract>() {
    @java.lang.Override
    public CreateContract parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreateContract(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateContract> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateContract> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public me.kay.protobuf.proto.CreateContract getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

