// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PbStudent.proto

package me.kay.grpc.proto;

public final class PbStudent {
  private PbStudent() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_kay_proto_StudentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_kay_proto_StudentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_kay_proto_StudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_kay_proto_StudentResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017PbStudent.proto\022\014me.kay.proto\"$\n\016Stude" +
      "ntRequest\022\022\n\nstudent_id\030\001 \001(\005\";\n\017Student" +
      "Response\022\022\n\nstudent_id\030\001 \001(\005\022\024\n\014student_" +
      "Name\030\002 \001(\t2a\n\016StudentService\022O\n\016GetStude" +
      "ntById\022\034.me.kay.proto.StudentRequest\032\035.m" +
      "e.kay.proto.StudentResponse\"\000B \n\021me.kay." +
      "grpc.protoB\tPbStudentP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_me_kay_proto_StudentRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_me_kay_proto_StudentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_kay_proto_StudentRequest_descriptor,
        new java.lang.String[] { "StudentId", });
    internal_static_me_kay_proto_StudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_me_kay_proto_StudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_kay_proto_StudentResponse_descriptor,
        new java.lang.String[] { "StudentId", "StudentName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
