// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PbStudent.proto

package me.kay.grpc.proto;

public interface StudentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:me.kay.proto.StudentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 student_id = 1;</code>
   * @return The studentId.
   */
  int getStudentId();
}
