// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PbStudent.proto

package me.kay.grpc.proto;

public interface StudentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:me.kay.proto.StudentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 student_id = 1;</code>
   * @return The studentId.
   */
  int getStudentId();

  /**
   * <code>string student_Name = 2;</code>
   * @return The studentName.
   */
  java.lang.String getStudentName();
  /**
   * <code>string student_Name = 2;</code>
   * @return The bytes for studentName.
   */
  com.google.protobuf.ByteString
      getStudentNameBytes();
}
