// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PbStudent.proto

package me.kay.decorator.grpc;

public final class PbStudent {
  private PbStudent() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_kay_proto_NameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_kay_proto_NameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_kay_proto_AgeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_kay_proto_AgeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_kay_proto_StudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_kay_proto_StudentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_kay_proto_StudentResponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_kay_proto_StudentResponseList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_kay_proto_StreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_kay_proto_StreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_kay_proto_StreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_kay_proto_StreamResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017PbStudent.proto\022\014me.kay.proto\"#\n\013NameR" +
      "equest\022\024\n\014student_name\030\001 \001(\t\"!\n\nAgeReque" +
      "st\022\023\n\013student_age\030\001 \001(\005\"<\n\017StudentRespon" +
      "se\022\023\n\013student_age\030\001 \001(\005\022\024\n\014student_Name\030" +
      "\002 \001(\t\"M\n\023StudentResponseList\0226\n\017studentR" +
      "esponse\030\001 \003(\0132\035.me.kay.proto.StudentResp" +
      "onse\"%\n\rStreamRequest\022\024\n\014request_info\030\001 " +
      "\001(\t\"&\n\016StreamResponse\022\024\n\014request_info\030\001 " +
      "\001(\t2\327\002\n\016StudentService\022N\n\020GetStudentByNa" +
      "me\022\031.me.kay.proto.NameRequest\032\035.me.kay.p" +
      "roto.StudentResponse\"\000\022N\n\017GetStudentByAg" +
      "e\022\030.me.kay.proto.AgeRequest\032\035.me.kay.pro" +
      "to.StudentResponse\"\0000\001\022Z\n\027GetStudentsWra" +
      "pperByAge\022\030.me.kay.proto.AgeRequest\032!.me" +
      ".kay.proto.StudentResponseList\"\000(\001\022I\n\006Bi" +
      "Talk\022\033.me.kay.proto.StreamRequest\032\034.me.k" +
      "ay.proto.StreamResponse\"\000(\0010\001B\032\n\013me.kay." +
      "grpcB\tPbStudentP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_me_kay_proto_NameRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_me_kay_proto_NameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_kay_proto_NameRequest_descriptor,
        new java.lang.String[] { "StudentName", });
    internal_static_me_kay_proto_AgeRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_me_kay_proto_AgeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_kay_proto_AgeRequest_descriptor,
        new java.lang.String[] { "StudentAge", });
    internal_static_me_kay_proto_StudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_me_kay_proto_StudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_kay_proto_StudentResponse_descriptor,
        new java.lang.String[] { "StudentAge", "StudentName", });
    internal_static_me_kay_proto_StudentResponseList_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_me_kay_proto_StudentResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_kay_proto_StudentResponseList_descriptor,
        new java.lang.String[] { "StudentResponse", });
    internal_static_me_kay_proto_StreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_me_kay_proto_StreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_kay_proto_StreamRequest_descriptor,
        new java.lang.String[] { "RequestInfo", });
    internal_static_me_kay_proto_StreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_me_kay_proto_StreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_kay_proto_StreamResponse_descriptor,
        new java.lang.String[] { "RequestInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
