// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PbStudent.proto

package me.kay.decorator.grpc;

public interface StreamResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:me.kay.proto.StreamResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request_info = 1;</code>
   * @return The requestInfo.
   */
  java.lang.String getRequestInfo();
  /**
   * <code>string request_info = 1;</code>
   * @return The bytes for requestInfo.
   */
  com.google.protobuf.ByteString
      getRequestInfoBytes();
}
